import React from 'react';
import { Star, Rocket, Users, Store, BarChart3, User, KeyRound, Pencil, Trash2, Search, List, AlertTriangle, CheckCircle, FileText, MessageSquare, TrendingUp, MapPin, Sparkles, Ban, Clock, Smile, Frown, Meh, Plus, LogOut, Eye, EyeOff, Lock, ArrowUpDown, ArrowUp, ArrowDown, ArrowRight, ArrowLeft, X, Loader2, LayoutGrid, LayoutList, Shield, Sun, HelpCircle, BadgeCheck, ChevronDown } from 'lucide-react';

export const Icons = {
  Star: (props: any) => <Star {...props} />,
  Rocket: (props: any) => <Rocket {...props} />,
  Users: (props: any) => <Users {...props} />,
  Store: (props: any) => <Store {...props} />,
  BarChart3: (props: any) => <BarChart3 {...props} />,
  User: (props: any) => <User {...props} />,
  KeyRound: (props: any) => <KeyRound {...props} />,
  Pencil: (props: any) => <Pencil {...props} />,
  Trash2: (props: any) => <Trash2 {...props} />,
  Search: (props: any) => <Search {...props} />,
  List: (props: any) => <List {...props} />,
  LayoutGrid: (props: any) => <LayoutGrid {...props} />,
  LayoutList: (props: any) => <LayoutList {...props} />,
  AlertTriangle: (props: any) => <AlertTriangle {...props} />,
  CheckCircle: (props: any) => <CheckCircle {...props} />,
  FileText: (props: any) => <FileText {...props} />,
  MessageSquare: (props: any) => <MessageSquare {...props} />,
  TrendingUp: (props: any) => <TrendingUp {...props} />,
  MapPin: (props: any) => <MapPin {...props} />,
  Sparkles: (props: any) => <Sparkles {...props} />,
  Ban: (props: any) => <Ban {...props} />,
  Clock: (props: any) => <Clock {...props} />,
  Smile: (props: any) => <Smile {...props} />,
  Frown: (props: any) => <Frown {...props} />,
  Meh: (props: any) => <Meh {...props} />,
  Plus: (props: any) => <Plus {...props} />,
  LogOut: (props: any) => <LogOut {...props} />,
  Eye: (props: any) => <Eye {...props} />,
  ArrowUpDown: (props: any) => <ArrowUpDown {...props} />,
  ArrowUp: (props: any) => <ArrowUp {...props} />,
  ArrowDown: (props: any) => <ArrowDown {...props} />,
  ArrowRight: (props: any) => <ArrowRight {...props} />,
  ArrowLeft: (props: any) => <ArrowLeft {...props} />,
  X: (props: any) => <X {...props} />,
  Loader2: (props: any) => <Loader2 {...props} />,
  Shield: (props: any) => <Shield {...props} />,
  EyeOff: (props: any) => <EyeOff {...props} />,
  Lock: (props: any) => <Lock {...props} />,
  Sun: (props: any) => <Sun {...props} />,
  HelpCircle: (props: any) => <HelpCircle {...props} />,
  BadgeCheck: (props: any) => <BadgeCheck {...props} />,
  ChevronDown: (props: any) => <ChevronDown {...props} />,
};
